version: "3.7"

services:

  doris_es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - node.name=doris_es
      - cluster.name=doris_es
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
    networks:
      - dorisnet
    healthcheck:
      test: [ "CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health" ]


  doris_app:
    build: ..
    restart: always
    ports:
      - 5088:5088
    depends_on:
      - doris_es
    networks:
      - dorisnet

networks:
  dorisnet:
    driver: bridge
